services:
    blockonomics_sylius_plugin.form.type.gateway_configuration:
        class: Blockonomics\SyliusPlugin\Form\Type\BlockonomicsGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: blockonomics, label: "Blockonomics" }
            - { name: form.type }