# Delete these routes and define your own shop routes here

Blockonomics_sylius_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Blockonomics\SyliusPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

Blockonomics_sylius_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Blockonomics\SyliusPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
